### ISSUE TITLE
Error thrown

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10003]
```
? What is the ID of your plugin? foo
? What is the name of your plugin? Foo
? Describe what your plugin does? Does Foo you know?
? Comma-separated list of categories foo,bar
? What is the name of the author? Steve Clay
? What the email address of the author? steve@mrclay.org
? What plugin project URL? http://www.mrclay.org/
? What is the author's Github username? mrclay
? What is the minimum required Elgg version? 2.0

events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-hypeplugin/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-hypeplugin/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-hypeplugin/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at PhpGenerator.plugin (/usr/local/lib/node_modules/generator-hypeplugin/app/index.js:111:10)
    at /usr/local/lib/node_modules/generator-hypeplugin/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by hypeJunction** [comment]
I think this was meant for the generator. I beed to push the latest version. I think something is missing on npm

**Comment by hypeJunction** [comment]
FYI, it's fixed now. The problem was with FS editor failing to use dot file templates, it didn't like `.gitignore` as a template name. Removing the dot fixes the issue.
