### ISSUE TITLE
local docs testing is broken

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10321]
```
$ grunt
module.js:457
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/lib/findup-sync.js:15:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by jdalsem** [comment]
i did not have this problem a few weeks back when testing docs... @hypeJunction did you use grunt today when doing the releases?

**Comment by jdalsem** [comment]
Still a problem in 2017 #10741 but maybe only for @mrclay
