### ISSUE TITLE
Cannot build docs locally

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10741]
`grunt` fails with:

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/lib/findup-sync.js:15:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by jdalsem** [comment]
Still have this problem? Our local build works fine

**Comment by mrclay** [comment]
Yep, upgraded yarn (and node), added "glob" as a direct dependency, no luck.

**Comment by jdalsem** [comment]
try
```
 npm uninstall -g grunt-cli

npm install -g grunt-cli
```

**Comment by jdalsem** [comment]
As @jeabakker and i have no problem building locally, it could be just you :) Closing until we have more info and steps to reproduce
