### ISSUE TITLE
elgg-3: find cause of fatal error

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11771]
```apache
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Elgg\\Database\\Plugins::Elgg\\Database\\{closure}() must be an instance of ElggPlugin, instance of ElggObject given in vendor/elgg/elgg/engine/classes/Elgg/Database/Plugins.php:662\n
Stack trace:\n
#0 [internal function]: Elgg\\Database\\Plugins->Elgg\\Database\\{closure}(Object(ElggObject), Object(ElggObject))\n
#1 vendor/elgg/elgg/engine/classes/Elgg/Database/Plugins.php(671): usort(Array, Object(Closure))\n
#2 vendor/elgg/elgg/engine/classes/Elgg/Di/DefinitionLoader.php(40): Elgg\\Database\\Plugins->find('active')\n
#3 vendor/elgg/elgg/engine/classes/Elgg/Di/ServiceProvider.php(280): Elgg\\Di\\DefinitionLoader->getDefinitions()\n
#4 [internal function]: Elgg\\Di\\ServiceProvider->Elgg\\Di\\{closure}(Object(Elgg\\Di\\ServiceProvider))\n
#5 vendor/elgg/elgg/ in vendor/elgg/elgg/engine/classes/Elgg/Database/Plugins.php on line 662, 

referer: https://localhost/admin
```

**Comment by hypeJunction** [comment]
Stale cache?

**Comment by jeabakker** [comment]
I also get it after flushing all cache

Op 2 mrt. 2018 6:56 p.m. schreef "Ismayil Khayredinov" <
notifications@github.com>:
