### ISSUE TITLE
Elgg 3.0.2 - Error in accessing "Plugin" page in admin section after migration

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12562]
I have just migrated my site from 2.3.9 to 3.0.2 and after the migration, I am getting the following error whenever I am trying to access the plugin page in the admin section:
```
ELGG.CRITICAL: Exception at time 1556725237:
InvalidArgumentException: key must be string or integer in /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Cache/CompositeCache.php:90
Stack trace:
#0 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/Plugins.php(339): Elgg\Cache\CompositeCache->save(Array, Object(ElggPlugin))
#1 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/ElggPlugin.php(1338): Elgg\Database\Plugins->cache(Object(ElggPlugin))
#2 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php(1566): ElggPlugin->cache()
#3 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/ElggEntity.php(140): ElggEntity->load(Object(stdClass))
#4 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php(312): ElggEntity->__construct(Object(stdClass))
#5 /home/ckarma/public_html/vendor/elgg/elgg/engine/lib/entities.php(77): Elgg\Database\EntityTable->rowToElggStar(Object(stdClass))
#6 [internal function]: entity_row_to_elggstar(Object(stdClass))
#7 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database.php(411): call_user_func('entity_row_to_e...', Object(stdClass))
#8 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database.php(200): Elgg\Database->getResults(Object(Elgg\Database\Select), 'entity_row_to_e...', false, Array)
#9 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/EntityTable.php(487): Elgg\Database->getData(Object(Elgg\Database\Select), 'entity_row_to_e...')
#10 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/Entities.php(157): Elgg\Database\EntityTable->fetch(Object(Elgg\Database\Select), Array)
#11 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/Entities.php(226): Elgg\Database\Entities->get(false, 0, NULL)
#12 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/Repository.php(87): Elgg\Database\Entities->execute()
#13 /home/ckarma/public_html/vendor/elgg/elgg/engine/lib/entities.php(546): Elgg\Database\Repository::find(Array)
#14 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/Plugins.php(838): elgg_get_entities(Array)
#15 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Database/Plugins.php(249): Elgg\Database\Plugins->find('all')
#16 /home/ckarma/public_html/vendor/elgg/elgg/engine/lib/plugins.php(18): Elgg\Database\Plugins->generateEntities()
#17 /home/ckarma/public_html/vendor/elgg/elgg/views/default/admin/plugins.php(15): _elgg_generate_plugin_entities()
#18 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(522): include('/home/ckarma/pu...')
#19 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(455): Elgg\ViewsService->renderViewFile('admin/plugins', Array, 'default', true)
#20 /home/ckarma/public_html/vendor/elgg/elgg/engine/lib/views.php(251): Elgg\ViewsService->renderView('admin/plugins', Array, 'default')
#21 /home/ckarma/public_html/vendor/elgg/elgg/engine/lib/admin.php(646): elgg_view('admin/plugins', Array)
#22 [internal function]: _elgg_admin_page_handler(Array, 'admin', Object(Elgg\Request))
#23 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(291): call_user_func('_elgg_admin_pag...', Array, 'admin', Object(Elgg\Request))
#24 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(251): Elgg\Router->getResponseFromHandler('_elgg_admin_pag...', Object(Elgg\Request))
#25 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(124): Elgg\Router->prepareResponse(Object(Elgg\Http\Request))
#26 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(98): Elgg\Router->getResponse(Object(Elgg\Http\Request))
#27 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(467): Elgg\Router->route(Object(Elgg\Http\Request))
#28 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(362): Elgg\Application->run()
#29 /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(418): Elgg\Application::route(Object(Elgg\Http\Request))
#30 /home/ckarma/public_html/index.php(8): Elgg\Application::index()
#31 {main}
```

InvalidArgumentException: key must be string or integer in /home/ckarma/public_html/vendor/elgg/elgg/engine/classes/Elgg/Cache/CompositeCache.php:90

On further investigation, I found out that the following values were used for $key variable:

- ["tidypics_plus","tidypics_plus"]
- ["jb_overlay","jb_overlay"]
- ["online_cv","online_cv"]
- ["internship","internship"]
- ["hypeDiscovery","hypeDiscovery"]
- ["discussions_tools","discussions_tools"]
- ["embed_extended","embed_extended"]
- ["questions","questions"]
- ["community_plugin","community_plugin"]
- ["company_review","company_review"]
- ["coaching","coaching"]
- ["facebook_sdk","facebook_sdk"]
- ["facebook_connect_","facebook_connect_"]
- ["privacy_notification","privacy_notification"]
- ["garbagecollector_extended","garbagecollector_extended"]
- ["exam_portal","exam_portal"]

How to fix this?
It will be very helpful if anyone can provide me with a solution ASAP. (The issue is on my production site)

**Comment by jeabakker** [comment]
somehow `$plugin->getID()` is returning an array in https://github.com/Elgg/Elgg/blob/375e96f940a719a16e78335125d8c88b5d0ab5b1/engine/classes/Elgg/Database/Plugins.php#L345

Were there any errors during the upgrading process. because it would seem that there are 2 `title` fields in the metadata table for the plugin entities. resulting in an array instead of a string. https://github.com/Elgg/Elgg/blob/375e96f940a719a16e78335125d8c88b5d0ab5b1/engine/classes/ElggPlugin.php#L123-L125

**Comment by rohit1290** [comment]
Yes, there were breaks in the upgrading process. My upgrde.php timed out on every 15 mins and that is why i had to re run the migration again and again. There might be a scenario where a particular migration would have happened twice. My service provider has some settings that even if the script timed out, it will automatically start again in background.

Thank you for pointing out the two titles issue in metadata. It was indeed, duplicate title and description for same entity_guid.

I was able to solve the problem by removing one of the duplicate entries.
