### ISSUE TITLE
Issue with Site Secret after Moving Servers

### ISSUE THREAD

**Issue by mfierro95** [Elgg/Elgg#13284]
Hi there-- I'm currently working with a customer to move an instance between servers. First, we ran into the issue of mismatch database prefixes and were able to get those changed to have the site loading properly but the next day, we received this error: 
```
[19-Aug-2020 15:28:02 UTC] [2020-08-19 15:28:02] ELGG.CRITICAL: Exception at time 1597850882:
ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/arditopl/public_html/pacecommons/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:37
Stack trace:
#0 /home/arditopl/public_html/pacecommons/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/arditopl/...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Doctrine\\DBAL\\Q...')
#2 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Database/QueryBuilder.php(16): spl_autoload_call('Doctrine\\DBAL\\Q...')
#3 /home/arditopl/public_html/pacecommons/vendor/composer/ClassLoader.php(444): include('/home/arditopl/...')
#4 /home/arditopl/public_html/pacecommons/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/arditopl/...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('Elgg\\Database\\Q...')
#6 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Database/Select.php(8): spl_autoload_call('Elgg\\Database\\Q...')
#7 /home/arditopl/public_html/pacecommons/vendor/composer/ClassLoader.php(444): include('/home/arditopl/...')
#8 /home/arditopl/public_html/pacecommons/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/arditopl/...')
#9 [internal function]: Composer\Autoload\ClassLoader->loadClass('Elgg\\Database\\S...')
#10 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Database/ConfigTable.php(154): spl_autoload_call('Elgg\\Database\\S...')
#11 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/BootService.php(98): Elgg\Database\ConfigTable->getAll()
#12 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Application/BootHandler.php(99): Elgg\BootService->boot(Object(Elgg\Di\ServiceProvider))
#13 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Application/BootHandler.php(47): Elgg\Application\BootHandler->bootServices()
#14 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Application.php(215): Elgg\Application\BootHandler->__invoke()
#15 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Application.php(468): Elgg\Application->bootCore()
#16 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Application.php(359): Elgg\Application->run()
#17 /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/classes/Elgg/Application.php(415): Elgg\Application::route(Object(Elgg\Http\Request))
#18 /home/arditopl/public_html/pacecommons/index.php(8): Elgg\Application::index()
#19 {main}
 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) at /home/arditopl/public_html/pacecommons/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:37)"} {"backtrace":[],"process_id":18322,"memory_peak_usage":"4 MB","memory_usage":"4 MB","url":"/pacecommons/blog/all","ip":"98.175.165.5","http_method":"GET","server":"arditople.org","referrer":null}
```

We've double-checked that the secret is the same within the database and files within the database tables `arditopl_el2`.`elggdm_datalists` and in /home/arditopl/public_html/pacecommons/vendor/elgg/elgg/engine/tests/classes/Elgg/Mocks/Database/ConfigTable.php, even hardcoding within some of the configuration files but no avail. 

Site is running version 3.3.8 on PHP 7.2 and using MariaDB 10.3

Is there anything I'm missing while troubleshooting? Thanks so much in advance!

**Comment by iionly** [comment]
Are you 100% sure that PHP 7.2 is used by the installation? Couldn't it be that it's 7.0 instead for some reason? That might explain the error (at least a Google search gave some indication that it might be related to a too-old PHP version).

**Comment by mfierro95** [comment]
The site is running PHP 7.2.32 specifically, I've changed the version to 7.0 and to 7.3 to triple check but the version changes didn't help. 

I should also mention that the site is on a cPanel server running Litespeed as well

**Comment by jeabakker** [comment]
Your error seems related to a PHP error not an Elgg error.

What I could find about the error is that that class constants now can have a visibility modifier (see https://www.php.net/manual/en/language.oop5.constants.php#example-194, also https://stackoverflow.com/questions/51567998/parse-error-syntax-error-unexpected-const-t-const-expecting-variable-t-v)
This was added in PHP 7.1

The error comes from https://github.com/doctrine/dbal/blob/0c9a646775ef549eb0a213a4f9bd4381d9b4d934/lib/Doctrine/DBAL/Query/QueryBuilder.php#L37

Are you sure you're running PHP 7.2+? You can check this by enabling PHPInfo in the settings file https://github.com/Elgg/Elgg/blob/edd691bb10a44e11e892d4b200d14016fd65bde5/elgg-config/settings.example.php#L347-L355
and going to https://yoursite/phpinfo (as and admin). However this won't work if Elgg isn't running.
So create a simple php file with just
```php
<?
phpinfo();
```

**Comment by mfierro95** [comment]
The site is running 7.2.32-- I created the phpinfo.php file on the domain to confirm that it was running the proper version in my previous response. The file can be found here: https://arditople.org/pacecommons/phpinfo.php.

This sounds like something within the code that was given to me as the migration started, which is not something I'll be able to troubleshoot-- I'm wondering if they were running a lower version of PHP that is conflicting with the current server settings.

I'll take a look at these suggestions, thank you!

**Comment by jeabakker** [comment]
Any update on this issue

**Comment by jdalsem** [comment]
Closing this because of inactivity
