### ISSUE TITLE
investigate issues in upgrade travis job regarding index sizes

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#13329]
https://travis-ci.com/github/Elgg/Elgg/jobs/404492941#L1136

**Comment by jdalsem** [comment]
== 20200331083912 AddEntityGuidNameIndexToAnnotations: migrating
PDOException: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. in /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:168
Stack trace:
#0 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(168): PDO->exec('ALTER TABLE `t_...')
#1 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(126): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE `t_...')
#2 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(573): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE `t_...', Array)
#3 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(932): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('t_i_elgg_annota...', Object(Phinx\Db\Util\AlterInstructions))
#4 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(497): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#5 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(406): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
#6 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(497): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#7 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TablePrefixAdapter.php(457): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
#8 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TablePrefixAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#9 /home/travis/build/Elgg/Elgg/vendor/cakephp/collection/CollectionTrait.php(64): Phinx\Db\Plan\Plan->Phinx\Db\Plan\{closure}(Object(Phinx\Db\Plan\AlterTable), 'annotations')
#10 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(147): Cake\Collection\Collection->each(Object(Closure))
#11 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(721): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TablePrefixAdapter))
#12 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(628): Phinx\Db\Table->executeActions(true)
#13 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(687): Phinx\Db\Table->update()
#14 /home/travis/build/Elgg/Elgg/engine/schema/migrations/20200331083912_add_entity_guid_name_index_to_annotations.php(29): Phinx\Db\Table->save()
#15 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(125): AddEntityGuidNameIndexToAnnotations->change()
#16 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(391): Phinx\Migration\Manager\Environment->executeMigration(Object(AddEntityGuidNameIndexToAnnotations), 'up', false)
#17 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(365): Phinx\Migration\Manager->executeMigration('prod', Object(AddEntityGuidNameIndexToAnnotations), 'up', false)
#18 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('prod', 20200331083912, false)
#19 /home/travis/build/Elgg/Elgg/vendor/symfony/console/Command/Command.php(255): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#20 /home/travis/build/Elgg/Elgg/vendor/symfony/console/Application.php(992): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#21 /home/travis/build/Elgg/Elgg/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#22 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#23 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(243): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\StreamOutput))
#24 /home/travis/build/Elgg/Elgg/vendor/robmorgan/phinx/src/Phinx/Wrapper/TextWrapper.php(129): Phinx\Wrapper\TextWrapper->executeRun(Array)
#25 /home/travis/build/Elgg/Elgg/engine/classes/Elgg/Application.php(564): Phinx\Wrapper\TextWrapper->getMigrate()
#26 /home/travis/build/Elgg/Elgg/engine/classes/Elgg/Cli/UpgradeCommand.php(39): Elgg\Application::migrate()
#27 /home/travis/build/Elgg/Elgg/vendor/symfony/console/Command/Command.php(255): Elgg\Cli\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /home/travis/build/Elgg/Elgg/vendor/symfony/console/Application.php(992): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /home/travis/build/Elgg/Elgg/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Elgg\Cli\UpgradeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /home/travis/build/Elgg/Elgg/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /home/travis/build/Elgg/Elgg/engine/classes/Elgg/Cli.php(156): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/travis/build/Elgg/Elgg/elgg-cli(54): Elgg\Cli->run(false)
#33 {main}

**Comment by jdalsem** [comment]
Not happening at the moment. We recently switched to Github Actions from Travis, so might have been fixed as part of that move
