### ISSUE TITLE
Captcha image won't show

### ISSUE THREAD

**Issue by xuelinsmann** [Elgg/Elgg#13639]
add captcha plugin, but the image won't show in registration
https://elgg.org/plugins/914006

**Comment by xuelinsmann** [comment]
Disable all plugins, only enable captcha plugin , the image won't show still

**Comment by xuelinsmann** [comment]
[Sat Aug 14 17:05:11.457125 2021] [php7:notice] [pid 13724] [client ::1:50624] [2021-08-14 02:05:11] ELGG.CRITICAL: Exception at time 1628931911:\nError: Call to undefined function imagettftext() in /Library/WebServer/Documents/socjoy/mod/captcha/views/default/resources/captcha/captcha.php:23\nStack trace:\n#0 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(516): include()\n#1 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(449): Elgg\\ViewsService->renderViewFile('resources/captc...', Array, 'default', true)\n#2 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/lib/views.php(404): Elgg\\ViewsService->renderView('resources/captc...', Array)\n#3 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/classes/Elgg/Router.php(280): elgg_view_resource('captcha/captcha', Array)\n#4 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/classes/Elgg/Router.php(128): Elgg\\Router->prepareResponse(Object(Elgg\\Http\\Request))\n#5 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/classes/Elgg/Router.php(104): Elgg\\Router->getResponse(Object(Elgg\\Http\\Request))\n#6 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/classes/Elgg/Application.php(479): Elgg\\Router->route(Object(Elgg\\Http\\Request))\n#7 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/classes/Elgg/Application.php(360): Elgg\\Application->run()\n#8 /Library/WebServer/Documents/socjoy/vendor/elgg/elgg/engine/classes/Elgg/Application.php(416): Elgg\\Application::route(Object(Elgg\\Http\\Request))\n#9 /Library/WebServer/Documents/socjoy/index.php(8): Elgg\\Application::index()\n#10 {main}\n {"exception":"[object] (Error(code: 0): Call to undefined function imagettftext() at /Library/WebServer/Documents/socjoy/mod/captcha/views/default/resources/captcha/captcha.php:23)"} {"backtrace":[],"process_id":13724,"memory_peak_usage":"2 MB","memory_usage":"2 MB","url":"/socjoy/captcha/e2f39bab997cea5c8f2256f8d74ba81f","ip":"::1","http_method":"GET","server":"localhost","referrer":"http://localhost/socjoy/register"}\n, referer: http://localhost/socjoy/register

**Comment by xuelinsmann** [comment]
Call to undefined function imagettftext()
Looks like an issue on my server, need to install php for gd and free type
https://stackoverflow.com/questions/7290958/php-fatal-error-call-to-undefined-function-imagettftext
