### ISSUE TITLE
master: fatal error after garbagecollector run (groups_entity table damaged)

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#8744]
Doesn't happen on Elgg 1.X, so I don't think it's a MariaDB issue this time. Output is:

Fatal Error.

An exception occurred while executing 'SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4':

SQLSTATE[HY000]: General error: 144 Table './elgg20/elgg_groups_entity' is marked as crashed and last (automatic?) repair failed

QUERY: SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4

DatabaseException Object
(
[message:protected] => An exception occurred while executing 'SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4':

SQLSTATE[HY000]: General error: 144 Table './elgg20/elgg_groups_entity' is marked as crashed and last (automatic?) repair failed

QUERY: SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4
[string:Exception:private] => exception 'DatabaseException' with message 'An exception occurred while executing 'SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4':

SQLSTATE[HY000]: General error: 144 Table './elgg20/elgg_groups_entity' is marked as crashed and last (automatic?) repair failed

QUERY: SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4' in /home/xxx/public_html/elgg20/engine/classes/Elgg/Database.php:413
Stack trace:
#0 /home/xxx/public_html/elgg20/engine/classes/Elgg/Database.php(366): Elgg\Database->executeQuery('SELECT DISTINCT...', Object(Doctrine\DBAL\Connection))
#1 /home/xxx/public_html/elgg20/engine/classes/Elgg/Database.php(200): Elgg\Database->getResults('SELECT DISTINCT...', '', false)
#2 /home/xxx/public_html/elgg20/engine/classes/Elgg/Database/EntityTable.php(595): Elgg\Database->getData('SELECT DISTINCT...')
#3 /home/xxx/public_html/elgg20/engine/lib/entities.php(505): Elgg\Database\EntityTable->fetchFromSql('SELECT DISTINCT...', NULL)
#4 /home/xxx/public_html/elgg20/engine/classes/Elgg/Database/EntityTable.php(467): _elgg_fetch_entities_from_sql('SELECT DISTINCT...', NULL)
#5 /home/xxx/public_html/elgg20/engine/lib/entities.php(491): Elgg\Database\EntityTable->getEntities(Array)
#6 [internal function]: elgg_get_entities(Array)
#7 /home/xxx/public_html/elgg20/engine/lib/entities.php(616): call_user_func('elgg_get_entiti...', Array)
#8 /home/xxx/public_html/elgg20/mod/custom_index/views/default/resources/index.php(49): elgg_list_entities(Array)
#9 /home/xxx/public_html/elgg20/engine/classes/Elgg/ViewsService.php(352): include('/home/xxx/pu...')
#10 /home/xxx/public_html/elgg20/engine/classes/Elgg/ViewsService.php(294): Elgg\ViewsService->renderViewFile('resources/index', Array, 'default', true)
#11 /home/xxx/public_html/elgg20/engine/lib/views.php(475): Elgg\ViewsService->renderView('resources/index', Array)
#12 /home/xxx/public_html/elgg20/engine/lib/pagehandler.php(229): elgg_view_resource('index')
#13 [internal function]: elgg_front_page_handler(Array, '')
#14 /home/xxx/public_html/elgg20/engine/classes/Elgg/Router.php(80): call_user_func('elgg_front_page...', Array, '')
#15 /home/xxx/public_html/elgg20/engine/classes/Elgg/Application.php(385): Elgg\Router->route(Object(Elgg\Http\Request))
#16 /home/xxx/public_html/elgg20/engine/classes/Elgg/Application.php(341): Elgg\Application->run()
#17 /home/xxx/public_html/elgg20/index.php(8): Elgg\Application::index()
#18 {main}
[code:protected] => 0
[file:protected] => /home/xxx/public_html/elgg20/engine/classes/Elgg/Database.php
[line:protected] => 413
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/Database.php
[line] => 366
[function] => executeQuery
[class] => Elgg\Database
[type] => ->
[args] => Array
(
[0] => SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4
[1] => Doctrine\DBAL\Connection Object
(
[_conn:protected] => Doctrine\DBAL\Driver\PDOConnection Object
(
)

[_config:protected] => Doctrine\DBAL\Configuration Object
(
[_attributes:protected] => Array
(
)

)

[_eventManager:protected] => Doctrine\Common\EventManager Object
(
[_listeners:Doctrine\Common\EventManager:private] => Array
(
)

)

[_expr:protected] => Doctrine\DBAL\Query\Expression\ExpressionBuilder Object
(
[connection:Doctrine\DBAL\Query\Expression\ExpressionBuilder:private] => Doctrine\DBAL\Connection Object
*RECURSION*
)

[_isConnected:Doctrine\DBAL\Connection:private] => 1
[autoCommit:Doctrine\DBAL\Connection:private] => 1
[_transactionNestingLevel:Doctrine\DBAL\Connection:private] => 0
[_transactionIsolationLevel:Doctrine\DBAL\Connection:private] =>
[_nestTransactionsWithSavepoints:Doctrine\DBAL\Connection:private] =>
[_params:Doctrine\DBAL\Connection:private] => Array
(
[dbname] => xxx
[user] => xxx
[password] => xxx
[host] => localhost
[charset] => utf8
[driver] => pdo_mysql
)

[platform:Doctrine\DBAL\Connection:private] => Doctrine\DBAL\Platforms\MySqlPlatform Object
(
[doctrineTypeMapping:protected] =>
[doctrineTypeComments:protected] =>
[_eventManager:protected] => Doctrine\Common\EventManager Object
(
[_listeners:Doctrine\Common\EventManager:private] => Array
(
)

)

[_keywords:protected] =>
)

[_schemaManager:protected] =>
[_driver:protected] => Doctrine\DBAL\Driver\PDOMySql\Driver Object
(
)

[_isRollbackOnly:Doctrine\DBAL\Connection:private] =>
[defaultFetchMode:protected] => 5
)

)

)

[1] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/Database.php
[line] => 200
[function] => getResults
[class] => Elgg\Database
[type] => ->
[args] => Array
(
[0] => SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4
[1] =>
[2] =>
)

)

[2] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/Database/EntityTable.php
[line] => 595
[function] => getData
[class] => Elgg\Database
[type] => ->
[args] => Array
(
[0] => SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4
)

)

[3] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/lib/entities.php
[line] => 505
[function] => fetchFromSql
[class] => Elgg\Database\EntityTable
[type] => ->
[args] => Array
(
[0] => SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4
[1] =>
)

)

[4] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/Database/EntityTable.php
[line] => 467
[function] => _elgg_fetch_entities_from_sql
[args] => Array
(
[0] => SELECT DISTINCT e.*, st.name, st.description FROM elgg_entities e JOIN elgg_groups_entity st ON (e.guid = st.guid) WHERE ((e.type = 'group')) AND (e.site_guid IN (1)) AND ((1 = 1) AND (e.enabled = 'yes')) ORDER BY e.time_created desc LIMIT 0, 4
[1] =>
)

)

[5] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/lib/entities.php
[line] => 491
[function] => getEntities
[class] => Elgg\Database\EntityTable
[type] => ->
[args] => Array
(
[0] => Array
(
[offset] => 0
[limit] => 4
[full_view] =>
[list_type_toggle] =>
[pagination] =>
[no_results] =>
[type] => group
[count] =>
)

)

)

[6] => Array
(
[function] => elgg_get_entities
[args] => Array
(
[0] => Array
(
[offset] => 0
[limit] => 4
[full_view] =>
[list_type_toggle] =>
[pagination] =>
[no_results] =>
[type] => group
[count] =>
)

)

)

[7] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/lib/entities.php
[line] => 616
[function] => call_user_func
[args] => Array
(
[0] => elgg_get_entities
[1] => Array
(
[offset] => 0
[limit] => 4
[full_view] =>
[list_type_toggle] =>
[pagination] =>
[no_results] =>
[type] => group
[count] =>
)

)

)

[8] => Array
(
[file] => /home/xxx/public_html/elgg20/mod/custom_index/views/default/resources/index.php
[line] => 49
[function] => elgg_list_entities
[args] => Array
(
[0] => Array
(
[type] => group
[limit] => 4
[full_view] =>
[list_type_toggle] =>
[pagination] =>
)

)

)

[9] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/ViewsService.php
[line] => 352
[args] => Array
(
[0] => /home/xxx/public_html/elgg20/mod/custom_index/views/default/resources/index.php
)

[function] => include
)

[10] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/ViewsService.php
[line] => 294
[function] => renderViewFile
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => resources/index
[1] => Array
(
)

[2] => default
[3] => 1
)

)

[11] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/lib/views.php
[line] => 475
[function] => renderView
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => resources/index
[1] => Array
(
)

)

)

[12] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/lib/pagehandler.php
[line] => 229
[function] => elgg_view_resource
[args] => Array
(
[0] => index
)

)

[13] => Array
(
[function] => elgg_front_page_handler
[args] => Array
(
[0] => Array
(
)

[1] =>
)

)

[14] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/Router.php
[line] => 80
[function] => call_user_func
[args] => Array
(
[0] => elgg_front_page_handler
[1] => Array
(
)

[2] =>
)

)

[15] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/Application.php
[line] => 385
[function] => route
[class] => Elgg\Router
[type] => ->
[args] => Array
(
[0] => Elgg\Http\Request Object
(
[attributes] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[request] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[query] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[__elgg_uri] => /
)

)

[server] => Symfony\Component\HttpFoundation\ServerBag Object
(
[parameters:protected] => Array
(
[HTTP_HOST] => xxx
[HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0
[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[HTTP_ACCEPT_LANGUAGE] => de-DE,en-US;q=0.7,en;q=0.3
[HTTP_ACCEPT_ENCODING] => gzip, deflate
[HTTP_DNT] => 1
[HTTP_COOKIE] => Elgg=xxx
[HTTP_CONNECTION] => keep-alive
[PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[SERVER_SIGNATURE] => <address>Apache/2.4.10 (Linux/SUSE) Server at xxx Port 80</address>

[SERVER_SOFTWARE] => Apache/2.4.10 (Linux/SUSE)
[SERVER_NAME] => xxx
[SERVER_ADDR] => 127.0.0.2
[SERVER_PORT] => 80
[REMOTE_ADDR] => 127.0.0.1
[DOCUMENT_ROOT] => /xxx
[REQUEST_SCHEME] => http
[CONTEXT_PREFIX] => /~xxx
[CONTEXT_DOCUMENT_ROOT] => /home/xxx/public_html
[SERVER_ADMIN] => xxx
[SCRIPT_FILENAME] => /home/xxx/public_html/elgg20/index.php
[REMOTE_PORT] => 38748
[GATEWAY_INTERFACE] => CGI/1.1
[SERVER_PROTOCOL] => HTTP/1.1
[REQUEST_METHOD] => GET
[QUERY_STRING] =>
[REQUEST_URI] => /~xxx/elgg20/
[SCRIPT_NAME] => /~xxx/elgg20/index.php
[PHP_SELF] => /~xxx/elgg20/index.php
[REQUEST_TIME_FLOAT] => 1437225368.577
[REQUEST_TIME] => 1437225368
)

)

[files] => Symfony\Component\HttpFoundation\FileBag Object
(
[parameters:protected] => Array
(
)

)

[cookies] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[Elgg] => xxx
)

)

[headers] => Symfony\Component\HttpFoundation\HeaderBag Object
(
[headers:protected] => Array
(
[host] => Array
(
[0] => xxx
)

[user-agent] => Array
(
[0] => Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0
)

[accept] => Array
(
[0] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
)

[accept-language] => Array
(
[0] => de-DE,en-US;q=0.7,en;q=0.3
)

[accept-encoding] => Array
(
[0] => gzip, deflate
)

[dnt] => Array
(
[0] => 1
)

[cookie] => Array
(
[0] => Elgg=xxx
)

[connection] => Array
(
[0] => keep-alive
)

)

[cacheControl:protected] => Array
(
)

)

[content:protected] =>
[languages:protected] =>
[charsets:protected] =>
[encodings:protected] =>
[acceptableContentTypes:protected] =>
[pathInfo:protected] =>
[requestUri:protected] => /~xxx/elgg20/
[baseUrl:protected] =>
[basePath:protected] =>
[method:protected] =>
[format:protected] =>
[session:protected] =>
[locale:protected] =>
[defaultLocale:protected] => en
)

)

)

[16] => Array
(
[file] => /home/xxx/public_html/elgg20/engine/classes/Elgg/Application.php
[line] => 341
[function] => run
[class] => Elgg\Application
[type] => ->
[args] => Array
(
)

)

[17] => Array
(
[file] => /home/xxx/public_html/elgg20/index.php
[line] => 8
[function] => index
[class] => Elgg\Application
[type] => ::
[args] => Array
(
)

)

)

[previous:Exception:private] =>
)

**Comment by iionly** [comment]
Problem seems to be that the ariadb engine of MariaDB can't handle delayed queries. To prevent the crash it seems the only way currently to use "max_delayed_threads = 0" in my.cnf for MariaDB.
