### ISSUE TITLE
insert errors for register action (1.12.0)

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#8980]
i have seen several times errors reported when new accounts are setup, along the lines of the error log code below. i do have a customised login action but it is only intended to facilitate integrating the profile manager login process into an ajax form and doesn't add any functionality. anyone know why this might be occurring? thanks

```
Duplicate entry 'a_username' for key 'username'

 QUERY: INSERT into users_entity
			(guid, name, username, password, salt, password_hash, email, language)
			values (19454, 'displayname', 'a_username', '', '', 'a_longcode', 'email@email.com', 'en')

	DatabaseException Object
(
    [message:protected] =&gt; Duplicate entry &#039;a_username&#039; for key &#039;username&#039;

 QUERY: INSERT into users_entity
			(guid, name, username, password, salt, password_hash, email, language)
			values (19454, &#039;displayname&#039;, &#039;a_username&#039;,password,salt, password_hash,;email@email.com&#039;, &#039;en&#039;)
    [string:Exception:private] =&gt; exception &#039;DatabaseException&#039; with message &#039;Duplicate entry &#039;a_username&#039; for key &#039;username&#039;

 QUERY: INSERT into users_entity
			(guid, name, username, password, salt, password_hash, email, language)
			values (19454, &#039;displayname&#039;, &#039;a_username&#039;, password,salt, password_hash,;email@email.com&#039;, &#039;en&#039;)&#039; in /mysite/engine/classes/Elgg/Database.php:406
Stack trace:
#0 /mysite/engine/classes/Elgg/Database.php(215): Elgg\Database-&gt;executeQuery(&#039;INSERT into use...&#039;, Resource id #2)
#1 /mysite/engine/classes/ElggUser.php(157): Elgg\Database-&gt;insertData(&#039;INSERT into use...&#039;)
#2 /mysite/engine/classes/ElggEntity.php(1592): ElggUser-&gt;create()
#3 /mysite/engine/classes/Elgg/Database/UsersTable.php(429): ElggEntity-&gt;save()
#4 /mysite/engine/lib/users.php(317): Elgg\Database\UsersTable-&gt;register(&#039;a_username&#039;, &#039;password039;, &#039;displayname&#039;, &#039;email&#039;, false)
#5 /mysite/mod/ureka_theme/actions/register.php(31): register_user(&#039;a_username&#039;, &#039;a_username039;, &#039;display_name&#039;, &#039;email#039;)
#6 /mysite/engine/classes/Elgg/ActionsService.php(88): include(&#039;/mysite...&#039;)
#7 /mysite/engine/classes/Elgg/ActionsService.php(70): Elgg\ActionsService::includeFile(&#039;/mysite...&#039;)
#8 /mysite/engine/lib/actions.php(20): Elgg\ActionsService-&gt;execute(&#039;register&#039;)
#9 [internal function]: _elgg_action_handler(Array, &#039;action&#039;)
#10 /mysite/engine/classes/Elgg/Router.php(80): call_user_func(&#039;_elgg_action_ha...&#039;, Array, &#039;action&#039;)
#11 /mysite/index.php(60): Elgg\Router-&gt;route(Object(Elgg\Http\Request))
#12 {main}
    [code:protected] =&gt; 0
    [file:protected] =&gt; /mysite/engine/classes/Elgg/Database.php
    [line:protected] =&gt; 406
    [trace:Exception:private] =&gt; Array
        (
            [0] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/classes/Elgg/Database.php
                    [line] =&gt; 215
                    [function] =&gt; executeQuery
                    [class] =&gt; Elgg\Database
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; INSERT into users_entity
			(guid, name, username, password, salt, password_hash, email, language)
			values (19454, &#039;a_username&#039;, &#039;display_name&#039;, password,salt, password_hash,;email@email.com&#039;, &#039;en&#039;)
                            [1] =&gt; Resource id #2
                        )

                )

            [1] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/classes/ElggUser.php
                    [line] =&gt; 157
                    [function] =&gt; insertData
                    [class] =&gt; Elgg\Database
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; INSERT into users_entity
			(guid, name, username, password, salt, password_hash, email, language)
			values (19454, &#039;username&#039;, &#039;display_name&#039;, password,salt, password_hash,;email@email.com;, &#039;en&#039;)
                        )

                )

            [2] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/classes/ElggEntity.php
                    [line] =&gt; 1592
                    [function] =&gt; create
                    [class] =&gt; ElggUser
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                        )

                )

            [3] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/classes/Elgg/Database/UsersTable.php
                    [line] =&gt; 429
                    [function] =&gt; save
                    [class] =&gt; ElggEntity
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                        )

                )

            [4] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/lib/users.php
                    [line] =&gt; 317
                    [function] =&gt; register
                    [class] =&gt; Elgg\Database\UsersTable
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; a_username
                            [1] =&gt; password
                            [2] =&gt; displayname
                            [3] =&gt; email@email.com
                            [4] =&gt; 
                        )

                )

            [5] =&gt; Array
                (
                    [file] =&gt; /mysite/mod/ureka_theme/actions/register.php
                    [line] =&gt; 31
                    [function] =&gt; register_user
                    [args] =&gt; Array
                        (
                            [0] =&gt; a_username
                            [1] =&gt; password
                            [2] =&gt; display_name
                            [3] =&gt; email@email.com
                        )

                )

            [6] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/classes/Elgg/ActionsService.php
                    [line] =&gt; 88
                    [args] =&gt; Array
                        (
                            [0] =&gt; /mysite/mod/ureka_theme/actions/register.php
                        )

                    [function] =&gt; include
                )

            [7] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/classes/Elgg/ActionsService.php
                    [line] =&gt; 70
                    [function] =&gt; includeFile
                    [class] =&gt; Elgg\ActionsService
                    [type] =&gt; ::
                    [args] =&gt; Array
                        (
                            [0] =&gt; /mysite/mod/ureka_theme/actions/register.php
                        )

                )

            [8] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/lib/actions.php
                    [line] =&gt; 20
                    [function] =&gt; execute
                    [class] =&gt; Elgg\ActionsService
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; register
                        )

                )

            [9] =&gt; Array
                (
                    [function] =&gt; _elgg_action_handler
                    [args] =&gt; Array
                        (
                            [0] =&gt; Array
                                (
                                    [0] =&gt; register
                                )

                            [1] =&gt; action
                        )

                )

            [10] =&gt; Array
                (
                    [file] =&gt; /mysite/engine/classes/Elgg/Router.php
                    [line] =&gt; 80
                    [function] =&gt; call_user_func
                    [args] =&gt; Array
                        (
                            [0] =&gt; _elgg_action_handler
                            [1] =&gt; Array
                                (
                                    [0] =&gt; register
                                )

                            [2] =&gt; action
                        )

                )

            [11] =&gt; Array
                (
                    [file] =&gt; /mysite/index.php
                    [line] =&gt; 60
                    [function] =&gt; route
                    [class] =&gt; Elgg\Router
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; Elgg\Http\Request Object
                                (
                                    [attributes] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                )

                                        )

                                    [request] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                    [__elgg_token] =&gt; token
                                                    [__elgg_ts] =&gt; timestamp
                                                    [name] =&gt; displayname
                                                    [email] =&gt; email@email.com
                                                    [username] =&gt; a_username
                                                    [password] =&gt; password
                                                    [password2] =&gt; password
                                                    [friend_guid] =&gt; 0
                                                    [invitecode] =&gt; 
                                                    [accept_terms] =&gt; yes
                                                    [submit] =&gt; joyn us
                                                )

                                        )

                                    [query] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                    [__elgg_uri] =&gt; /action/register
                                                )

                                        )

                                    [server] =&gt; Symfony\Component\HttpFoundation\ServerBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                    [USER] =&gt; nginx
                                                    [HOME] =&gt; /home/nginx
                                                    [FCGI_ROLE] =&gt; RESPONDER
                                                    [QUERY_STRING] =&gt; __elgg_uri=/action/register&amp;
                                                    [REQUEST_METHOD] =&gt; POST
                                                    [CONTENT_TYPE] =&gt; application/x-www-form-urlencoded
                                                    [CONTENT_LENGTH] =&gt; 242
                                                    [SCRIPT_NAME] =&gt; /index.php
                                                    [REQUEST_URI] =&gt; /action/register
                                                    [DOCUMENT_URI] =&gt; /index.php
                                                    [DOCUMENT_ROOT] =&gt; /mysite/ureka
                                                    [SERVER_PROTOCOL] =&gt; HTTP/1.1
                                                    [HTTPS] =&gt; on
                                                    [GATEWAY_INTERFACE] =&gt; CGI/1.1
                                                    [SERVER_SOFTWARE] =&gt; nginx
                                                    [REMOTE_ADDR] =&gt; IP
                                                    [REMOTE_PORT] =&gt; port
                                                    [SERVER_ADDR] =&gt; IP
                                                    [SERVER_PORT] =&gt; 443
                                                    [SERVER_NAME] =&gt; www.ureka.org
                                                    [REDIRECT_STATUS] =&gt; 200
                                                    [SCRIPT_FILENAME] =&gt; /mysite/index.php
                                                    [HTTP_HOST] =&gt; www.ureka.org
                                                    [HTTP_ACCEPT] =&gt; text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                                                    [HTTP_ACCEPT_ENCODING] =&gt; gzip, deflate
                                                    [HTTP_ACCEPT_LANGUAGE] =&gt; en-US,en;q=0.8
                                                    [HTTP_CACHE_CONTROL] =&gt; max-age=0
                                                    [HTTP_CONTENT_LENGTH] =&gt; 242
                                                    [HTTP_CONTENT_TYPE] =&gt; application/x-www-form-urlencoded
                                                    [HTTP_COOKIE] =&gt; Elgg=cookie code.; _pk_ses.1.e8a2=*
                                                    [HTTP_ORIGIN] =&gt; https://www.ureka.org
                                                    [HTTP_REFERER] =&gt; https://www.ureka.org/joyn
                                                    [HTTP_UPGRADE_INSECURE_REQUESTS] =&gt; 1
                                                    [HTTP_USER_AGENT] =&gt; Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36
                                                    [PHP_SELF] =&gt; /index.php
                                                    [REQUEST_TIME_FLOAT] =&gt; 1443101413.7182
                                                    [REQUEST_TIME] =&gt; 1443101413
                                                )

                                        )

                                    [files] =&gt; Symfony\Component\HttpFoundation\FileBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                )

                                        )

                                    [cookies] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                    [Elgg] =&gt; code
                                                    [_pk_id_1_e8a2] =&gt; code.
                                                    [_pk_ses_1_e8a2] =&gt; *
                                                )

                                        )

                                    [headers] =&gt; Symfony\Component\HttpFoundation\HeaderBag Object
                                        (
                                            [headers:protected] =&gt; Array
                                                (
                                                    [content-type] =&gt; Array
                                                        (
                                                            [0] =&gt; application/x-www-form-urlencoded
                                                        )

                                                    [content-length] =&gt; Array
                                                        (
                                                            [0] =&gt; 242
                                                        )

                                                    [host] =&gt; Array
                                                        (
                                                            [0] =&gt; www.ureka.org
                                                        )

                                                    [accept] =&gt; Array
                                                        (
                                                            [0] =&gt; text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
                                                        )

                                                    [accept-encoding] =&gt; Array
                                                        (
                                                            [0] =&gt; gzip, deflate
                                                        )

                                                    [accept-language] =&gt; Array
                                                        (
                                                            [0] =&gt; en-US,en;q=0.8
                                                        )

                                                    [cache-control] =&gt; Array
                                                        (
                                                            [0] =&gt; max-age=0
                                                        )

                                                    [cookie] =&gt; Array
                                                        (
                                                            [0] =&gt; Elgg=cookie code; _pk_ses.1.e8a2=*
                                                        )

                                                    [origin] =&gt; Array
                                                        (
                                                            [0] =&gt; https://www.ureka.org
                                                        )

                                                    [referer] =&gt; Array
                                                        (
                                                            [0] =&gt; https://www.ureka.org/joyn
                                                        )

                                                    [upgrade-insecure-requests] =&gt; Array
                                                        (
                                                            [0] =&gt; 1
                                                        )

                                                    [user-agent] =&gt; Array
                                                        (
                                                            [0] =&gt; useragent
                                                        )

                                                )

                                            [cacheControl:protected] =&gt; Array
                                                (
                                                    [max-age] =&gt; 0
                                                )

                                        )

                                    [content:protected] =&gt; 
                                    [languages:protected] =&gt; 
                                    [charsets:protected] =&gt; 
                                    [encodings:protected] =&gt; 
                                    [acceptableContentTypes:protected] =&gt; 
                                    [pathInfo:protected] =&gt; 
                                    [requestUri:protected] =&gt; 
                                    [baseUrl:protected] =&gt; 
                                    [basePath:protected] =&gt; 
                                    [method:protected] =&gt; 
                                    [format:protected] =&gt; 
                                    [session:protected] =&gt; 
                                    [locale:protected] =&gt; 
                                    [defaultLocale:protected] =&gt; en
                                )

                        )

                )

        )

    [previous:Exception:private] =&gt; 
)
```

**Comment by juho-jaakkola** [comment]
It sounds like something is overriding the core check that verifies the username does not already exists. Is the "a_username" just an example or is it always happening with that exact string?

**Comment by propertunist** [comment]
maybe that is profile manager, since it has it's own handling for that part of the process afaik.
i replaced all the traceable data with placeholders, so the 'a_username' is just an example.

**Comment by juho-jaakkola** [comment]
There are no reports of this happening in a stock Elgg, so this is most likely caused by a third-party plugin.

**Comment by propertunist** [comment]
ok thanks
